# vim:ft=ansible:
---
- name: users | create sudo-local group
  become: true
  group:
    name: sudo-local
    state: present

- name: users | add sudoers rule
  become: true
  copy:
    src: 01-users-sudo
    dest: /etc/sudoers.d/01-users-sudo
    validate: "visudo -cf %s"

- name: Create User
  become: true
  user:
    name: "{{ item.name }}"
    state: present
    groups: sudo,adm
    shell: "{{ item.shell | default('/bin/bash') }}"
  with_items:
    - "{{ users }}"

- name: Set authorized ssh key
  become: true
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
  with_subelements:
     - "{{ users }}"
     - authorized_keys
